import Link from 'next/link';
import { ArrowUpRight, CalendarDays, CheckCircle2, ClipboardCheck, CreditCard, MapPin } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';import {hasSupabaseConfig} from '@/lib/supabase/config';

const indiaToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default async function HandlerDashboard(){
 if(!hasSupabaseConfig())return <Setup/>;
 const db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)return <Setup/>;
 const [{data:profile},{data:assignments},{data:expenses}]=await Promise.all([
  db.from('profiles').select('full_name,handler_id').eq('id',user.id).maybeSingle(),
  db.from('event_assignments').select('id,status,responsibility,events(id,event_code,name,event_date,expected_arrival_time,client_name,activity:activities(name),city,venue,status)').eq('handler_id',user.id).order('assigned_at',{ascending:false}).limit(12),
  db.from('expenses').select('id,amount,status').eq('handler_id',user.id)
 ]);
 const rows=(assignments??[]).map((a:any)=>({...a,event:Array.isArray(a.events)?a.events[0]:a.events})).filter((a:any)=>a.event);const eventIds=rows.map((a:any)=>a.event.id);let pendingTasks=0;if(eventIds.length){const {count}=await db.from('checklist_items').select('id',{count:'exact',head:true}).in('event_id',eventIds).is('completed_at',null);pendingTasks=count??0}
 const today=indiaToday(),upcoming=rows.filter((a:any)=>a.event.event_date>=today&&a.event.status!=='cancelled'&&a.event.status!=='completed').sort((a:any,b:any)=>a.event.event_date.localeCompare(b.event.event_date));
 const next=upcoming[0],approved=(expenses??[]).filter((e:any)=>e.status==='approved'||e.status==='paid').reduce((n:number,e:any)=>n+Number(e.amount),0),waiting=(expenses??[]).filter((e:any)=>['submitted','under_review'].includes(e.status)).length;
 const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',hour12:false}).format(new Date()));
 return <main className="handler-home"><header className="real-dashboard-heading"><div><div className="eyebrow">YOUR WORKSPACE · {profile?.handler_id??'HANDLER'}</div><h1>Good {hour<12?'morning':hour<17?'afternoon':'evening'}, {profile?.full_name?.split(' ')[0]??'there'}</h1><p>Your assignments, event-day essentials and reimbursement status.</p></div><Link className="button button-secondary" href="/handler/my-id"><CreditCard size={15}/> View Your Profile</Link></header>
 <section className="handler-next-event">{next?<><div className="next-event-label"><CalendarDays size={14}/> NEXT ASSIGNMENT <span>{next.event.event_code}</span></div><div className="next-event-content"><div><h2>{next.event.name}</h2><p><MapPin size={14}/>{next.event.venue} · {next.event.city}</p><p>{next.event.activity?.name??'Activity not set'} · {next.event.client_name??'—'}</p><p><CalendarDays size={14}/>{new Date(`${next.event.event_date}T12:00:00`).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})} · Expected arrival {formatEventTime(next.event.expected_arrival_time)}</p></div><Link className="button button-primary" href={`/handler/events/${next.event.id}`}>Open event <ArrowUpRight size={14}/></Link></div></>:<div className="handler-no-event"><CalendarDays size={22}/><div><h2>No upcoming assignments</h2><p>New event assignments will appear here when your administrator assigns you.</p></div><Link href="/handler/events">View event history <ArrowUpRight size={14}/></Link></div>}</section>
 <section className="handler-summary-grid"><Link className="handler-summary" href="/handler/events"><span>Upcoming events</span><b>{upcoming.length}</b><small>Open your event schedule <ArrowUpRight size={12}/></small></Link><Link className="handler-summary" href="/handler/checklist"><span>Tasks to complete</span><b>{pendingTasks??0}</b><small>Across your assignments <ArrowUpRight size={12}/></small></Link><Link className="handler-summary" href="/handler/expenses"><span>Reimbursements in review</span><b>{waiting}</b><small>₹{approved.toLocaleString('en-IN')} approved to date <ArrowUpRight size={12}/></small></Link></section>
 <section className="real-panel handler-assignments"><header><div><h2>Your event schedule</h2><p>Assigned events and current operational status.</p></div><Link href="/handler/events">All events <ArrowUpRight size={13}/></Link></header>{!rows.length?<div className="real-empty">Your event history is ready for your first assignment.</div>:rows.slice(0,5).map((a:any)=><Link className="handler-event-line" href={`/handler/events/${a.event.id}`} key={a.id}><span className="handler-date-tile"><b>{new Date(`${a.event.event_date}T12:00:00`).toLocaleDateString('en-IN',{day:'2-digit'})}</b><small>{new Date(`${a.event.event_date}T12:00:00`).toLocaleDateString('en-IN',{month:'short'}).toUpperCase()}</small></span><div><b>{a.event.name}</b><small>{a.event.event_code} · {a.responsibility??'Event handler'} · {a.event.venue}, {a.event.city}</small></div><span className={`table-status ${a.event.status}`}>{a.event.status}</span><ArrowUpRight size={15}/></Link>)}</section>
 <div className="handler-shortcuts"><Link href="/handler/checklist"><ClipboardCheck size={17}/><span><b>Event tasks</b><small>Keep your assigned checklist current</small></span><ArrowUpRight size={14}/></Link><Link href="/handler/expenses"><CheckCircle2 size={17}/><span><b>Expenses & reimbursements</b><small>Track submissions and review status</small></span><ArrowUpRight size={14}/></Link></div>
 </main>
}
function formatEventTime(value:string|null){if(!value)return 'Not set';const [hour,minute]=value.slice(0,5).split(':').map(Number);return new Date(2000,0,1,hour,minute).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true})}
function Setup(){return <main className="data-page"><section className="config-notice"><div className="eyebrow">HANDLER WORKSPACE</div><h1>Connect your organization account</h1><p>Sign in with an active handler account after Supabase is configured for this workspace.</p><Link className="button button-secondary" href="/handler/login">Handler sign in</Link></section></main>}
