import Link from 'next/link';
import {ArrowUpRight,Clock3,ShieldCheck,UserRoundCheck} from 'lucide-react';
import {createClient} from '@/lib/supabase/server';

export default async function HandlerApplicationsPage(){
 const supabase=await createClient();const {data:allowed}=await supabase.rpc('can_review_handler_applications');
 if(!allowed)return <main className="data-page"><section className="data-state data-error"><ShieldCheck size={22}/><b>Verification access required</b><span>Your administrator account does not have permission to review handler identity applications.</span></section></main>;
 const {data,error,count}=await supabase.from('handler_applications').select('id,legal_name,email,phone,home_city_id,status,profile_completion,submitted_at,cities(name),handler_verifications(status,document_type)',{count:'exact'}).eq('status','verification_pending').order('submitted_at',{ascending:true}).limit(200);
 return <main className="data-page"><header className="data-heading"><div><div className="eyebrow">PEOPLE & TEAMS</div><h1>Pending verifications</h1><p>Review submitted profiles and identity documents before activating handler access.</p></div><span className="application-queue-count"><Clock3 size={15}/>{count??0} awaiting review</span></header><section className="data-panel"><div className="application-list-intro"><UserRoundCheck size={17}/><span>Only authorized verification reviewers can access identity documents. Applicants cannot receive assignments until approved.</span></div>{error?<div className="data-state data-error" role="alert">Applications could not be loaded. Check your reviewer access and try again.</div>:!data?.length?<div className="data-state"><ShieldCheck size={22}/><b>No pending applications</b><span>Submitted applications will appear here for authorized review.</span></div>:<div className="table-scroll"><table className="events-table"><thead><tr><th>APPLICANT</th><th>CITY</th><th>PROFILE</th><th>IDENTITY</th><th>SUBMITTED</th><th/></tr></thead><tbody>{data.map((app:any)=><tr key={app.id}><td><Link className="table-event-name" href={`/admin/handler-applications/${app.id}`}>{app.legal_name??'Name not provided'}</Link><small>{app.email} · {app.phone??'Phone not provided'}</small></td><td>{(Array.isArray(app.cities)?app.cities[0]?.name:app.cities?.name)??'—'}</td><td><span className="table-status active">{app.profile_completion}% complete</span></td><td><span className="table-status upcoming">{(Array.isArray(app.handler_verifications)?app.handler_verifications[0]?.status:app.handler_verifications?.status)??'PENDING'}</span><small>{(Array.isArray(app.handler_verifications)?app.handler_verifications[0]?.document_type:app.handler_verifications?.document_type)??'Document missing'}</small></td><td>{app.submitted_at?new Date(app.submitted_at).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'—'}</td><td><Link className="link-small" href={`/admin/handler-applications/${app.id}`}>Review <ArrowUpRight size={13}/></Link></td></tr>)}</tbody></table></div>}</section></main>
}
