'use client';
import {useMemo,useState} from 'react';import Link from 'next/link';import {ArrowUpRight,Bell,Download,Search} from 'lucide-react';import {createClient} from '@/lib/supabase/client';
type Row=Record<string,any>;
const formatEventTime=(value:string|null)=>{if(!value)return 'Not set';const [hour,minute]=value.slice(0,5).split(':').map(Number);return new Date(2000,0,1,hour,minute).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true})};
const text=(v:any)=>{if(v==null)return '—';if(typeof v==='object')return Object.values(v).filter(Boolean).join(' · ')||'—';if(typeof v==='string'&&v.includes('T')&&!Number.isNaN(Date.parse(v)))return new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});return String(v)};
const flatten=(o:any)=>Object.entries(o??{}).map(([k,v])=>`${k} ${typeof v==='object'?JSON.stringify(v):String(v??'')}`).join(' ').toLowerCase();
export default function AdminSection({section,title,intro,records,loadError}:{section:string;title:string;intro:string;records:Row[];loadError:boolean}){const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState('');const filtered=useMemo(()=>records.filter(r=>(!query||flatten(r).includes(query.toLowerCase()))&&(filter==='all'||(section==='live-events'?r.status===filter:section==='notifications'?filter==='unread'?!r.read_at:!!r.read_at:section==='reports'?r.status===filter:true))),[records,query,filter,section]);const cols=section==='live-events'?['name','event_code','event_date','expected_arrival_time','city','venue','team','health']:section==='calendar'?['event_date','expected_arrival_time','name','event_code','city','venue','team','status']:section==='attendance'?['handler','event','check_in_at','check_out_at','arrival_status','review_required']:section==='notifications'?['title','body','kind','created_at','href','read_at']:section==='audit-log'?['created_at','action','target_type','target_id','details','actor_id','actor_auth_id']:section==='reports'?['expense_date','event_id','handler_id','category','amount','status','review_note']:section==='settings'?['name','slug','created_at']:section==='clients'?['name','company','contact_person','email','home_city_id']:section==='venues'?['name','venue_type','address','city_id','client_id']:['name','unit','quantity_on_hand','reorder_level','city_id','active'];
 const rows=filtered.map(r=>{if(section==='live-events'){const team=r.event_assignments??[],attendance=r.attendance??[],present=attendance.filter((a:any)=>a.check_in_at),late=attendance.filter((a:any)=>a.arrival_status==='late'),tasks=r.checklist_items??[],done=tasks.filter((t:any)=>t.completed_at).length,missing=Math.max(0,team.length-present.length),issue=team.length===0||present.length===0,health=issue?'ACTION REQUIRED':missing||late.length||done<tasks.length?'ATTENTION REQUIRED':'ON TRACK';return {...r,team:`${team.length} assigned · ${present.length} checked in · ${late.length} late · ${missing} not arrived`,health}}
 if(section==='calendar')return {...r,expected_arrival_time:formatEventTime(r.expected_arrival_time),team:`${r.event_assignments?.length??0} assigned`};if(section==='attendance')return {...r,event:`${r.events?.event_code??''} · ${r.events?.name??''}`,handler:`${r.profiles?.full_name??''} · ${r.profiles?.handler_id??''}`};return r});
 function exportCsv(){const lines=[cols.join(','),...rows.map(r=>cols.map(c=>`"${String(r[c]??'').replaceAll('"','""')}"`).join(','))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\r\n')],{type:'text/csv;charset=utf-8'}));a.download=`eventops-${section}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 async function markRead(id:string){setBusy(id);setMessage('');try{const db=createClient();const {error}=await db.rpc('mark_notification_read',{p_notification_id:id});if(error)throw error;setMessage('Notification marked as read.');location.reload()}catch{setMessage('This notification could not be updated.');setBusy(null)}}
 const unread=records.filter(r=>!r.read_at).length;
 return <main className="data-page"><header className="data-page-heading"><div><div className="eyebrow">{section==='live-events'?'OPERATIONS MONITOR':section==='reports'?'INSIGHTS & EXPORTS':'ORGANIZATION WORKSPACE'}</div><h1>{title}</h1><p>{intro}</p></div>{(section==='reports'||section==='attendance')&&<button className="button button-secondary" onClick={exportCsv}><Download size={15}/> Export CSV</button>}{section==='clients'&&<span className="data-count">{records.length} records</span>}</header>{loadError&&<div className="inline-notice">Some records could not be loaded. Check your access and try again.</div>}{message&&<div className="inline-notice">{message}</div>}
 {(section==='live-events'||section==='calendar'||section==='attendance'||section==='reports'||section==='notifications')&&<div className="data-toolbar"><label className="data-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search these records"/></label>{section==='live-events'&&<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All event states</option><option value="active">Active events</option><option value="upcoming">Upcoming</option></select>}{section==='notifications'&&<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All notifications</option><option value="unread">Unread ({unread})</option><option value="read">Read</option></select>}{section==='reports'&&<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All expense statuses</option>{['submitted','under_review','approved','rejected','paid'].map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}</select>}{(section==='reports'||section==='attendance')&&<span className="data-count">{filtered.length} rows</span>}</div>}
 {section==='settings'&&records[0]&&<div className="settings-record"><span>Organization name</span><b>{records[0].name}</b><span>Workspace slug</span><b>{records[0].slug}</b><span>Created</span><b>{text(records[0].created_at)}</b><p>Organization settings are managed in Supabase for this deployment. Changes to identity and tenancy are restricted to platform administrators.</p></div>}
 {section==='notifications'&&!records.length&&<Empty>No notifications are addressed to your account.</Empty>}{section!=='settings'&&<div className="admin-data-table"><div className="admin-table-head">{cols.map(c=><span key={c}>{c.replaceAll('_',' ')}</span>)}{section==='notifications'&&<span>Action</span>}</div>{rows.map(r=><div className={`admin-table-row ${section==='notifications'&&!r.read_at?'unread-row':''}`} key={r.id}>{cols.map(c=><span key={c} className={c==='status'||c==='health'||c==='arrival_status'?'table-status-cell':''}>{c==='status'||c==='arrival_status'?<em className={`table-status ${String(r[c]).toLowerCase()}`}>{text(r[c])}</em>:c==='health'?<em className={`table-status ${r.health==='ON TRACK'?'active':r.health==='ATTENTION REQUIRED'?'attention':'action'}`}>{r.health}</em>:section==='notifications'&&c==='href'&&r.href?<Link href={r.href}>Open</Link>:text(r[c])}</span>)}{section==='notifications'&&<span>{r.read_at?'Read':<button className="text-button" onClick={()=>markRead(r.id)} disabled={busy===r.id}><Bell size={13}/> Mark read</button>}</span>}{section==='live-events'&&<span><Link className="table-open" href={`/admin/events/${r.id}`}>Open <ArrowUpRight size={12}/></Link></span>}{section==='calendar'&&<span><Link className="table-open" href={`/admin/events/${r.id}`}>Open <ArrowUpRight size={12}/></Link></span>}</div>)}{section==='live-events'&&<div className="admin-table-extra">Event health is derived from assignment coverage, recorded check-ins, arrival status and checklist completion.</div>}{section==='calendar'&&<div className="admin-table-extra"><Link href="/admin/events/new">Create an event <ArrowUpRight size={13}/></Link></div>}</div>}
 {(section==='live-events'||section==='calendar'||section==='attendance'||section==='reports'||section==='clients'||section==='venues'||section==='inventory'||section==='audit-log')&&!rows.length&&<Empty>{query?'No records match your search.':section==='live-events'?'No events are currently active.':`No ${title.toLowerCase()} records are available.`}</Empty>}</main>
}
function Empty({children}:{children:React.ReactNode}){return <div className="data-empty"><span>{children}</span></div>}


