'use client';
import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';import {ArrowLeft,ArrowRight,Check,MapPin,CalendarDays,Users} from 'lucide-react';import {createEvent,getWorkspaceContext} from '@/lib/services/events';import type {City,EventDraft} from '@/types/domain';
const steps=['Event basics','Place & schedule','Review'];
const blank:EventDraft={name:'',type:'Corporate Workshop',activity_id:null,client_id:null,description:'',city_id:'',date:'',start_time:'09:00',end_time:'16:00',venue:'',address:'',venue_access_time:'',expected_arrival_time:'',expected_participants:null,age_group:'',theme:'',status:'draft'};
export default function EventCreateForm(){const [step,setStep]=useState(0),[draft,setDraft]=useState(blank),[cities,setCities]=useState<City[]>([]),[activities,setActivities]=useState<{id:string;name:string}[]>([]),[clients,setClients]=useState<{id:string;name:string}[]>([]),[venues,setVenues]=useState<{id:string;name:string;address:string}[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState('');const router=useRouter();
 useEffect(()=>{getWorkspaceContext().then(ctx=>{setCities(ctx.cities);setActivities(ctx.activities);setClients(ctx.clients);if(ctx.cities[0])setDraft(d=>({...d,city_id:d.city_id||ctx.cities[0].id}))}).catch(e=>setError(e instanceof Error?e.message:'Could not load event setup.')).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!draft.city_id)return;const load=async()=>{try{const ctx=await getWorkspaceContext();const {data,error}=await ctx.supabase.from('venues').select('id,name,address').eq('city_id',draft.city_id).order('name');if(error)throw error;setVenues(data??[])}catch{setVenues([])}};load()},[draft.city_id]);
 function update<K extends keyof EventDraft>(key:K,value:EventDraft[K]){setDraft(d=>({...d,[key]:value}))}
 function next(){setError('');if(step===0&&draft.name.trim().length<3){setError('Enter an event name with at least 3 characters.');return}if(step===1){if(!draft.city_id||!draft.date||!draft.venue.trim()||draft.address.trim().length<5){setError('Choose a city and provide the date, venue and full address.');return}if(draft.end_time<=draft.start_time){setError('End time must be later than start time.');return}}setStep(s=>Math.min(s+1,2))}
 async function save(status:'draft'|'upcoming'){setBusy(true);setError('');setDone('');try{const result=await createEvent({...draft,status});setDone(`${result.event_code} · ${result.name} saved`);setTimeout(()=>router.push('/admin/events'),900)}catch(e){setError(e instanceof Error?e.message:'Event could not be saved. Try again.')}finally{setBusy(false)}}
 if(loading)return <div className="workflow"><div className="workflow-skeleton"/></div>;
 return <div className="workflow"><div className="workflow-top"><button className="back-link" onClick={()=>router.push('/admin/events')}><ArrowLeft size={14}/> Events</button><div className="workflow-steps">{steps.map((s,i)=><div className={'workflow-step '+(i===step?'current':i<step?'finished':'')} key={s}><span>{i<step?<Check size={13}/>:i+1}</span>{s}</div>)}</div></div><div className="workflow-card"><header><div className="eyebrow">NEW EVENT · STEP {step+1} OF 3</div><h1>{steps[step]}</h1><p>{step===0?'Start with the activity and client details.':step===1?'Choose a city, venue and schedule.':'Review the details before saving or publishing.'}</p></header>
 {step===0&&<div className="form-grid"><Field label="Event name" required><input autoFocus maxLength={120} value={draft.name} onChange={e=>update('name',e.target.value)} placeholder="e.g. Saturday Mosaic Workshop"/></Field><Field label="Event type" required><select value={draft.type} onChange={e=>update('type',e.target.value)}><option>Corporate Workshop</option><option>Birthday Party</option><option>Playdate / Special Occasion</option></select></Field><Field label="Activity"><select value={draft.activity_id??''} onChange={e=>update('activity_id',e.target.value||null)}><option value="">Choose an activity</option>{activities.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></Field><Field label="Client"><select value={draft.client_id??''} onChange={e=>update('client_id',e.target.value||null)}><option value="">Select a client (optional)</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Event description" wide><textarea rows={3} maxLength={4000} value={draft.description} onChange={e=>update('description',e.target.value)} placeholder="Purpose, key details or special considerations"/></Field></div>}
 {step===1&&<div className="form-grid"><Field label="City" required><select value={draft.city_id} onChange={e=>update('city_id',e.target.value)}>{cities.map(c=><option value={c.id} key={c.id}>{c.name} · {c.code}</option>)}</select></Field><Field label="Venue name" required><input list="event-venues" value={draft.venue} onChange={e=>{update('venue',e.target.value);const found=venues.find(v=>v.name===e.target.value);if(found)update('address',found.address)}} placeholder="Search or enter venue"/><datalist id="event-venues">{venues.map(v=><option key={v.id} value={v.name}/>)}</datalist></Field><Field label="Full address" required wide><input value={draft.address} onChange={e=>update('address',e.target.value)} placeholder="Street, district and postal code"/></Field><Field label="Event date" required><input type="date" min={new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())} value={draft.date} onChange={e=>update('date',e.target.value)}/></Field><Field label="Expected participants"><input type="number" min="0" value={draft.expected_participants??''} onChange={e=>update('expected_participants',e.target.value?Number(e.target.value):null)} placeholder="Optional"/></Field><Field label="Start time"><input type="time" value={draft.start_time} onChange={e=>update('start_time',e.target.value)}/></Field><Field label="End time"><input type="time" value={draft.end_time} onChange={e=>update('end_time',e.target.value)}/></Field><Field label="Venue access time"><input type="time" value={draft.venue_access_time} onChange={e=>update('venue_access_time',e.target.value)}/></Field><Field label="Expected handler arrival"><input type="time" value={draft.expected_arrival_time} onChange={e=>update('expected_arrival_time',e.target.value)}/></Field><Field label="Age group"><input value={draft.age_group} onChange={e=>update('age_group',e.target.value)} placeholder="e.g. 6–10 years"/></Field><Field label="Theme"><input value={draft.theme} onChange={e=>update('theme',e.target.value)} placeholder="Optional"/></Field></div>}
 {step===2&&<div className="review-summary"><Summary icon={<CalendarDays size={16}/>} label="Event" value={draft.name||'Untitled event'} detail={`${draft.type}${activities.find(a=>a.id===draft.activity_id)?` · ${activities.find(a=>a.id===draft.activity_id)?.name}`:''}`}/><Summary icon={<MapPin size={16}/>} label="Location" value={draft.venue||'Venue not set'} detail={`${cities.find(c=>c.id===draft.city_id)?.name??''} · ${draft.address}`}/><Summary icon={<CalendarDays size={16}/>} label="Schedule" value={draft.date||'Date not set'} detail={`${draft.start_time} – ${draft.end_time}${draft.expected_arrival_time?` · Handler arrival ${draft.expected_arrival_time}`:''}`}/><Summary icon={<Users size={16}/>} label="Participants & client" value={draft.expected_participants===null?'Participants to be confirmed':`${draft.expected_participants} expected participants`} detail={`${clients.find(c=>c.id===draft.client_id)?.name??'No client selected'}${draft.age_group?` · ${draft.age_group}`:''}`}/><p className="workflow-note">Event and handler IDs are assigned by the database. Assign handlers and add reimbursement rules from the saved event workspace.</p></div>}
 {error&&<div role="alert" className="workflow-error">{error}</div>}{done&&<div role="status" className="workflow-success">{done}</div>}<footer className="workflow-actions"><button type="button" className="button button-secondary" onClick={()=>step?setStep(step-1):router.push('/admin/events')}>{step?'Back':'Cancel'}</button><span/>{step<2?<button type="button" className="button button-primary" onClick={next}>Continue <ArrowRight size={14}/></button>:<><button type="button" disabled={busy} className="button button-secondary" onClick={()=>save('draft')}>{busy?'Saving…':'Save draft'}</button><button type="button" disabled={busy} className="button button-primary" onClick={()=>save('upcoming')}>{busy?'Publishing…':'Publish event'} <Check size={14}/></button></>}</footer></div></div>
}
function Field({label,required,wide,children}:{label:string;required?:boolean;wide?:boolean;children:React.ReactNode}){return <label className={'workflow-field '+(wide?'wide':'')}>{label}{required&&<i>Required</i>}{children}</label>}
function Summary({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="summary-row"><span className="summary-icon">{icon}</span><div><small>{label}</small><b>{value}</b><span>{detail}</span></div></div>}

