'use client';

import Link from 'next/link';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowLeft,Eye,EyeOff,LoaderCircle,ShieldCheck} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';
import {hasSupabaseConfig} from '@/lib/supabase/config';

export default function HandlerSignupForm(){
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);const router=useRouter();
  async function emailSignup(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setError('');const clean=email.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean)){setError('Enter a valid email address.');return}if(password.length<8){setError('Use a password with at least 8 characters.');return}if(!hasSupabaseConfig()){setError('This workspace is not connected to Supabase yet.');return}setBusy(true);try{const {data,error}=await createClient().auth.signUp({email:clean,password,options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=%2Fhandler%2Fonboarding`}});if(error){if(error.status===429)setError('There have been too many attempts. Wait a moment and try again.');else setError('We could not create your account. Check the Supabase email signup configuration or sign in if you already have an account.');return}if(data.session){router.replace('/handler/onboarding');router.refresh()}else{setSent(true)}}catch{setError('We could not reach the account service. Check your connection and try again.')}finally{setBusy(false)}}
  async function googleSignup(){if(busy)return;setError('');if(!hasSupabaseConfig()){setError('This workspace is not connected to Supabase yet.');return}setBusy(true);try{const {error}=await createClient().auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/auth/callback?next=%2Fhandler%2Fonboarding`}});if(error){setBusy(false);setError(error.code==='provider_disabled'?'Google sign-up is not enabled for this workspace yet. Please use email or contact your administrator.':'Google sign-up could not be started. Check the Google provider configuration and try again.')}}catch{setBusy(false);setError('Google sign-up could not be started. Check your connection and try again.')}}
  return <main className="auth-page"><section className="auth-brand"><Link href="/" className="entry-brand"><span className="entry-mark">S</span><span>SKILLO</span></Link><div className="auth-brand-copy"><div className="eyebrow">EVENT OPERATIONS</div><h1>Bring your skills<br/>to the right events.</h1><p>Create your account, complete verification and join the Skill-O event workforce.</p><div className="secure-note"><ShieldCheck size={17}/>Your profile stays pending until reviewed</div></div><small>Handler onboarding · Skill-O Crafts</small></section><section className="auth-content"><form className="auth-form" onSubmit={emailSignup} noValidate><Link href="/handler/login" className="back-link"><ArrowLeft size={14}/> Handler sign in</Link><div className="eyebrow">HANDLER REGISTRATION</div><h2>{sent?'Check your inbox':'Create your account'}</h2><p className="auth-description">{sent?'Use the secure confirmation link in your email to continue your application.':"Choose a sign-up method. Both continue through the same profile and verification steps."}</p>{sent?<div className="workflow-success" role="status">If this email can be registered, Supabase will send a confirmation link. After confirming, you can resume onboarding from this device or sign in again.</div>:<><label htmlFor="signup-email">Email address</label><input id="signup-email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" disabled={busy}/><div className="password-label"><label htmlFor="signup-password">Password</label><span>At least 8 characters</span></div><div className="password-input"><input id="signup-password" type={visible?'text':'password'} autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Create a password" disabled={busy}/><button type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)} disabled={busy}>{visible?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?<><LoaderCircle size={15} className="auth-spinner"/>Creating account...</>:'Sign up with Email'}</button><div className="auth-divider"><span>OR CONTINUE WITH</span></div><button type="button" className="google-submit" onClick={googleSignup} disabled={busy}>{busy?<><LoaderCircle size={15} className="auth-spinner"/>Connecting to Google...</>:<><GoogleMark/>Continue with Google</>}</button><p className="auth-footnote">Already registered? <Link href="/handler/login"><b>Sign in</b></Link><span>Account creation does not activate handler access. An administrator must verify your application.</span></p></>}</form></section></main>
}
function GoogleMark(){return <svg aria-hidden="true" width="17" height="17" viewBox="0 0 48 48"><path fill="#4285F4" d="M43.6 24.5c0-1.4-.1-2.8-.4-4.1H24v7.8h11a9.4 9.4 0 0 1-4.1 6.2v5.1h6.6c3.9-3.6 6.1-8.9 6.1-15Z"/><path fill="#34A853" d="M24 44c5.5 0 10.1-1.8 13.5-4.9l-6.6-5.1c-1.8 1.2-4 1.9-6.9 1.9-5.3 0-9.8-3.6-11.4-8.4H5.8v5.3A20 20 0 0 0 24 44Z"/><path fill="#FBBC05" d="M12.6 27.5a12 12 0 0 1 0-7.1v-5.3H5.8a20 20 0 0 0 0 17.7l6.8-5.3Z"/><path fill="#EA4335" d="M24 12c3 0 5.7 1 7.8 3l5.9-5.9C34.1 5.8 29.5 4 24 4A20 20 0 0 0 5.8 15.1l6.8 5.3C14.2 15.6 18.7 12 24 12Z"/></svg>}
