'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {useRouter} from 'next/navigation';import {ArrowUpRight,Bell,CalendarDays,Check,MapPin} from 'lucide-react';import {createClient} from '@/lib/supabase/client';
type Row=Record<string,any>;const fmt=(v:any)=>v?new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';
export default function HandlerSection({section,title,profile,records}:{section:string;title:string;profile:Row;records:Row[]}){const [busy,setBusy]=useState(''),[message,setMessage]=useState(''),[note,setNote]=useState<Record<string,string>>({}),router=useRouter();async function complete(id:string){setBusy(id);setMessage('');try{const db=createClient(),{error}=await db.rpc('complete_checklist',{p_item_id:id,p_note:note[id]||null});if(error)throw error;setMessage('Task marked complete.');router.refresh()}catch{setMessage('This task could not be updated. Try again or contact your event lead.')}finally{setBusy('')}}async function read(id:string){setBusy(id);try{const {error}=await createClient().rpc('mark_notification_read',{p_notification_id:id});if(error)throw error;router.refresh()}catch{setMessage('Notification could not be marked read.')}finally{setBusy('')}}
 return <main className="data-page"><header className="data-page-heading"><div><div className="eyebrow">HANDLER WORKSPACE · {profile.handler_id??'PROFILE'}</div><h1>{title}</h1><p>{section==='checklist'?'Keep event leads informed by recording task completion as it happens.':'Event assignments and updates addressed to you.'}</p></div></header>{message&&<div className="inline-notice">{message}</div>}
 {section==='checklist'&&<div className="handler-task-list">{records.map((t:any)=><article className={`handler-task ${t.completed_at?'is-complete':''}`} key={t.id}><div className="handler-task-marker">{t.completed_at?<Check size={16}/>:null}</div><div className="handler-task-main"><div className="handler-task-event"><Link href={`/handler/events/${t.event_id}`}>{t.events?.name??'Assigned event'} · {t.events?.event_code}</Link><span>{t.priority}</span></div><h2>{t.title}</h2>{t.completed_at?<small>Completed {fmt(t.completed_at)}</small>:<div className="task-complete-controls"><input aria-label="Optional completion note" value={note[t.id]??''} onChange={e=>setNote({...note,[t.id]:e.target.value})} placeholder="Optional note for the event lead"/><button className="button button-primary" onClick={()=>complete(t.id)} disabled={busy===t.id}>{busy===t.id?'Saving…':'Mark complete'}</button></div>}</div></article>)}{!records.length&&<div className="data-empty">No open checklist tasks are assigned to your current events.</div>}</div>}
 {section==='notifications'&&<div className="handler-notifications">{records.map(n=><article className={`handler-notification ${n.read_at?'':'unread-row'}`} key={n.id}><div className="notification-mark"><Bell size={16}/></div><div><h2>{n.title}</h2><p>{n.body}</p><small>{fmt(n.created_at)} · {n.kind.replaceAll('_',' ')}</small>{n.href&&<Link className="notification-link" href={n.href}>Open details <ArrowUpRight size={13}/></Link>}</div>{!n.read_at&&<button className="text-button" disabled={busy===n.id} onClick={()=>read(n.id)}>Mark read</button>}</article>)}{!records.length&&<div className="data-empty">You’re up to date. New assignments and event notices will appear here.</div>}</div>}
 </main>}

