import {notFound} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,FileCheck2,ShieldCheck} from 'lucide-react';
import {createClient} from '@/lib/supabase/server';
import HandlerApplicationReview from '@/components/handler-application-review';

export default async function HandlerApplicationReviewPage({params}:{params:Promise<{applicationId:string}>}){
 const {applicationId}=await params,supabase=await createClient();const {data:application,error}=await supabase.from('handler_applications').select('id,user_id,organization_id,email,legal_name,preferred_name,phone,home_city_id,profile_photo_path,emergency_contact_name,emergency_contact_phone,skills_experience,availability,preferred_event_locations,status,profile_completion,submitted_at,cities(name),handler_verifications(id,document_type,document_path,status,submitted_at,review_note)').eq('id',applicationId).maybeSingle();
 if(error||!application)notFound();const verification=Array.isArray(application.handler_verifications)?application.handler_verifications[0]:application.handler_verifications;const applicantCity=Array.isArray(application.cities)?application.cities[0]:application.cities;
 let documentUrl:string|null=null,photoUrl:string|null=null;if(verification?.document_path){const {data}=await supabase.storage.from('identity-documents').createSignedUrl(verification.document_path,300);documentUrl=data?.signedUrl??null;}if(application.profile_photo_path){const {data}=await supabase.storage.from('documents').createSignedUrl(application.profile_photo_path,300);photoUrl=data?.signedUrl??null;}
 const {data:allowed}=await supabase.rpc('can_review_handler_applications');if(!allowed)return <main className="data-page"><section className="data-state data-error"><ShieldCheck size={22}/><b>Verification access required</b><span>Your administrator account cannot review this application.</span><Link className="button button-secondary" href="/admin/handler-applications">Back to applications</Link></section></main>;
 return <main className="data-page"><header className="data-heading"><div><Link href="/admin/handler-applications" className="back-link"><ArrowLeft size={14}/> Handler applications</Link><div className="eyebrow">VERIFICATION REVIEW</div><h1>{application.legal_name??'Handler application'}</h1><p>{applicantCity?.name??'City not set'} · Submitted {application.submitted_at?new Date(application.submitted_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'}</p></div><span className={`table-status ${application.status==='verification_pending'?'upcoming':application.status}`}>{application.status.replaceAll('_',' ')}</span></header>
 <div className="application-review-layout"><section className="data-panel application-profile-panel"><div className="application-review-section"><div className="application-review-title"><div><div className="eyebrow">PROFILE COMPLETION · {application.profile_completion}%</div><h2>Applicant details</h2></div>{photoUrl?<img className="applicant-photo" src={photoUrl} alt="Applicant profile"/>:<div className="applicant-photo-placeholder">{application.legal_name?.slice(0,1)??'H'}</div>}</div><div className="application-facts"><b>Legal name</b><span>{application.legal_name??'—'}</span><b>Preferred name</b><span>{application.preferred_name??'—'}</span><b>Email</b><span>{application.email}</span><b>Phone</b><span>{application.phone??'—'}</span><b>Preferred city</b><span>{applicantCity?.name??'—'}</span><b>Emergency contact</b><span>{application.emergency_contact_name} · {application.emergency_contact_phone}</span><b>Skills / experience</b><span>{application.skills_experience}</span><b>Availability</b><span>{application.availability}</span></div></div><div className="application-review-section"><div className="application-review-title"><div><div className="eyebrow">RESTRICTED DOCUMENT</div><h2>Identity verification</h2></div><FileCheck2 size={19}/></div><div className="identity-review-meta"><span>Document type</span><b>{verification?.document_type??'Not submitted'}</b><span>Verification status</span><b>{verification?.status??'PENDING'}</b><span>Submitted</span><b>{verification?.submitted_at?new Date(verification.submitted_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'}</b></div>{documentUrl?<a className="button button-secondary" href={documentUrl} target="_blank" rel="noreferrer">Open secure identity document</a>:<p className="workflow-error">The identity document is unavailable or your role cannot access it.</p>}<p className="identity-privacy-note"><ShieldCheck size={14}/>Access is restricted to authorized handler verification reviewers. Do not copy ID numbers into notes.</p></div></section><HandlerApplicationReview applicationId={application.id} status={application.status} previousNote={verification?.review_note??null}/></div></main>
}
