'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Eye, EyeOff, ArrowRight, ShieldCheck } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
export default function Login(){const [show,setShow]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setError('Enter a valid work email address.');return;}if(password.length<8){setError('Password must be at least 8 characters.');return;}setBusy(true);try{const supabase=createClient();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;const target=new URLSearchParams(window.location.search).get('next')||'/';router.push(target.startsWith('/')&&!target.startsWith('//')?target:'/');router.refresh();}catch{setError('We couldn’t sign you in. Check your details and try again.');}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',display:'grid',gridTemplateColumns:'minmax(0,1.1fr) minmax(400px,.9fr)',background:'#fff'}}><section style={{background:'#172a39',color:'#fff',padding:'48px 7vw',display:'flex',flexDirection:'column',justifyContent:'space-between',minHeight:'100vh'}}><div className="brand" style={{padding:0}}><span className="brand-mark">E</span><span>eventops</span></div><div style={{maxWidth:500}}><div style={{color:'#d18b70',fontSize:10,fontWeight:700,letterSpacing:2,textTransform:'uppercase',marginBottom:20}}>EVENT WORKFORCE OPERATIONS</div><h1 style={{font:'700 clamp(32px,4vw,52px) Manrope',letterSpacing:-2,lineHeight:1.12,margin:'0 0 20px'}}>Every event,<br/>in good hands.</h1><p style={{color:'#afbdc6',fontSize:14,lineHeight:1.8,maxWidth:400}}>One considered workspace for the people, details, and decisions behind every event.</p><div style={{marginTop:42,borderTop:'1px solid #3a4d59',paddingTop:19,display:'flex',gap:11,alignItems:'center',color:'#c4d0d6',fontSize:11}}><ShieldCheck size={16} color="#d18b70"/>Secure access for your organization</div></div><div style={{fontSize:10,color:'#8ea0aa'}}>© 2026 EventOps · Skill-O Crafts</div></section><section style={{display:'grid',placeItems:'center',padding:30}}><form onSubmit={submit} style={{width:'min(100%,370px)'}}><div className="eyebrow">WELCOME BACK</div><h2 style={{font:'700 26px Manrope',letterSpacing:-.7,margin:'0 0 9px'}}>Sign in to EventOps</h2><p style={{color:'#84909a',fontSize:12,margin:'0 0 30px'}}>Use your organization email to continue.</p><label style={label}>Work email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" placeholder="you@organization.com" style={input}/><div style={{display:'flex',justifyContent:'space-between',marginTop:19}}><label style={label}>Password</label><a href="/forgot-password" style={{fontSize:10,color:'#b85c3f',fontWeight:600}}>Forgot password?</a></div><div style={{position:'relative'}}><input value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} autoComplete="current-password" placeholder="Enter your password" style={{...input,paddingRight:42}}/><button type="button" aria-label="Toggle password visibility" onClick={()=>setShow(!show)} style={{position:'absolute',right:12,top:12,border:0,background:'transparent',color:'#81909a'}}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>{error&&<div role="alert" style={{background:'#fcf0ed',color:'#a14e39',padding:'10px 12px',marginTop:15,fontSize:11,borderRadius:4}}>{error}</div>}<button className="button button-primary" disabled={busy} style={{width:'100%',justifyContent:'center',marginTop:23,padding:12,opacity:busy ? .7 : 1}}>{busy?'Signing in…':'Sign in'}{!busy&&<ArrowRight size={15}/>}</button><p style={{marginTop:18,textAlign:'center',fontSize:10,color:'#9aa4ab'}}>Access is managed by your organization administrator.</p></form></section></main>}
const label:React.CSSProperties={fontSize:11,fontWeight:600,color:'#425766',display:'block',marginBottom:8};const input:React.CSSProperties={width:'100%',height:41,border:'1px solid #dfe5e8',borderRadius:4,padding:'0 11px',outlineColor:'#b85c3f',fontSize:11,color:'#263d4c'};
