import {createClient} from '@supabase/supabase-js';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,password=process.env.DEMO_PASSWORD;
if(!url||!key||!password)throw new Error('Set NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, and DEMO_PASSWORD before seeding.');
const db=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});
async function user(email:string,name:string,role:'admin'|'handler',handlerId:string){let found:string|undefined;const {data:list}=await db.auth.admin.listUsers({perPage:1000});found=list.users.find(x=>x.email===email)?.id;if(!found){const {data,error}=await db.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:name}});if(error)throw error;found=data.user.id;}const {error}=await db.from('profiles').upsert({id:found,organization_id:orgId,role,handler_id:role==='handler'?handlerId:null,full_name:name,email,phone:'+91 98400 00000',job_title:role==='admin'?'Operations Lead':'Event Handler',team:role==='admin'?'Operations':'Field Crew',status:'active'},{onConflict:'id'});if(error)throw error;return found;}
let {data:org}=await db.from('organizations').select('id').eq('slug','skill-o').maybeSingle();if(!org){const {data,error}=await db.from('organizations').insert({name:'Skill-O Crafts',slug:'skill-o'}).select('id').single();if(error)throw error;org=data;}const orgId=org.id;
const admin=await user('ananya@skill-o.example','Ananya Krishnan','admin',''),h1=await user('arjun@skill-o.example','Arjun Menon','handler','SKL-CHN-00427'),h2=await user('meera@skill-o.example','Meera Iyer','handler','SKL-CHN-00428'),h3=await user('rohan@skill-o.example','Rohan Das','handler','SKL-BLR-00192');
const today=new Date();const day=(n:number)=>{const d=new Date(today);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const eventRows=[{event_code:'EVT-CHN-2026-012',name:'Skill-O DIY Crafts Workshop',type:'Workshop',event_date:day(0),start_time:'09:00',end_time:'16:30',venue:'The Residency Towers',address:'115 Sir Thyagaraya Road, T. Nagar',city:'Chennai',required_handlers:8,status:'active'},{event_code:'EVT-CHN-2026-013',name:'Brand Activation · Phoenix Marketcity',type:'Brand activation',event_date:day(2),start_time:'10:00',end_time:'19:00',venue:'Phoenix Marketcity',address:'142 Velachery Main Road',city:'Chennai',required_handlers:8,status:'upcoming'},{event_code:'EVT-CBE-2026-006',name:'Campus Makers Exhibition',type:'Exhibition',event_date:day(6),start_time:'08:30',end_time:'17:00',venue:'Codissia Trade Fair Complex',address:'Avinashi Road',city:'Coimbatore',required_handlers:12,status:'upcoming'}];
for(const e of eventRows){const {data:row,error}=await db.from('events').upsert({...e,organization_id:orgId,created_by:admin,organizer_name:'Skill-O Events'}, {onConflict:'event_code'}).select('id').single();if(error)throw error;for(const hid of [h1,h2,h3]){const {error:ae}=await db.from('event_assignments').upsert({event_id:row.id,handler_id:hid,responsibility:'Workshop facilitator',status:'acknowledged'},{onConflict:'event_id,handler_id'});if(ae)throw ae;}for(const [i,title]of ['Registration desk ready','Materials received','Seating arranged','Equipment checked'].entries()){const {error:ce}=await db.from('checklist_items').upsert({event_id:row.id,title,priority:i===0?'high':'normal',assigned_to:i%2?h2:h1,sort_order:i},{onConflict:'event_id,title'});if(ce)throw ce;}}
console.log(`Seeded Skill-O demo organization. Admin ${admin}; handlers ${h1}, ${h2}, ${h3}. All demo accounts use DEMO_PASSWORD.`);
