import { createClient } from '@supabase/supabase-js';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,password=process.env.DEMO_PASSWORD;
if(!url||!key||!password)throw new Error('Set NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, and DEMO_PASSWORD before seeding.');
const db=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});
const cities=[['Chennai','CHN'],['Bangalore','BLR'],['Mumbai','MUM'],['Hyderabad','HYD'],['Coimbatore','CBE'],['Ahmedabad','AMD'],['Pune','PUN']] as const;
async function must<T>(p:PromiseLike<{data:T|null,error:{message:string}|null}>):Promise<NonNullable<T>>{const {data,error}=await p;if(error)throw new Error(error.message);if(!data)throw new Error('Supabase returned no data');return data as NonNullable<T>}
const {data:existingOrg,error:orgErr}=await db.from('organizations').select('id').eq('slug','skill-o').maybeSingle();if(orgErr)throw new Error(orgErr.message);
const org=(existingOrg??await must(db.from('organizations').insert({name:'Skill-O Crafts',slug:'skill-o'}).select('id').single())) as {id:string};const orgId=org.id;
const cityRows=new Map<string,string>();
for(const [name,code] of cities){const row=await must(db.from('cities').upsert({organization_id:orgId,name,code,active:true,reimbursement_rules:{cab:800,food:350,currency:'INR'},local_contacts:[],inventory_base:`${name} craft base`},{onConflict:'organization_id,code'}).select('id').single()) as {id:string};cityRows.set(code,row.id)}
async function ensureUser(email:string,name:string,role:'super_admin'|'handler',cityCode:string|null){const {data:list,error:listErr}=await db.auth.admin.listUsers({perPage:1000});if(listErr)throw new Error(listErr.message);let id=list.users.find(u=>u.email===email)?.id;if(!id){const {data,error}=await db.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:name}});if(error)throw new Error(error.message);id=data.user.id;}const values={id,organization_id:orgId,role,home_city_id:cityCode?cityRows.get(cityCode):null,full_name:name,email,phone:'+91 98400 00000',job_title:role==='super_admin'?'Operations Lead':'Event Handler',team:role==='super_admin'?'Operations':'Field Crew',status:'active'};const {error}=await db.from('profiles').upsert(values,{onConflict:'id'});if(error)throw new Error(error.message);return id;}
const admin=await ensureUser('ananya@skill-o.example','Ananya Krishnan','super_admin',null);
const h1=await ensureUser('arjun@skill-o.example','Arjun Menon','handler','CHN'),h2=await ensureUser('meera@skill-o.example','Meera Iyer','handler','CHN'),h3=await ensureUser('rohan@skill-o.example','Rohan Das','handler','BLR');
const {data:activityRows,error:activityErr}=await db.from('activities').upsert(['Mosaic Art','Stuffed Toy Making','Paint & Plant','Fluid Art','Wooden Truck Making','Candle Making','Canvas Painting','Tote Bag Painting','Cut & Paint','Thank-you Cards'].map(name=>({organization_id:orgId,name,active:true})),{onConflict:'organization_id,name'}).select('id,name');if(activityErr)throw new Error(activityErr.message);
const activities=new Map((activityRows??[]).map(a=>[a.name,a.id]));
let {data:client,error:clientErr}=await db.from('clients').select('id').eq('organization_id',orgId).eq('name','Skill-O Studio').maybeSingle();if(clientErr)throw new Error(clientErr.message);if(!client){client=await must(db.from('clients').insert({organization_id:orgId,name:'Skill-O Studio',company:'Skill-O DIY Crafts',contact_person:'Events Desk',phone:'+91 44 5555 0123',email:'events@skill-o.example',home_city_id:cityRows.get('CHN')}).select('id').single())}
const venueDefs=[['The Residency Towers','CHN','115 Sir Thyagaraya Road, T. Nagar'],['Phoenix Marketcity','CHN','142 Velachery Main Road'],['Codissia Trade Fair Complex','CBE','Avinashi Road']];const venueIds:string[]=[];
for(const [name,code,address] of venueDefs){const {data:found,error:findErr}=await db.from('venues').select('id').eq('city_id',cityRows.get(code)!).eq('name',name).maybeSingle();if(findErr)throw new Error(findErr.message);const venue=found??await must(db.from('venues').insert({organization_id:orgId,city_id:cityRows.get(code),client_id:client.id,name,address,venue_type:'Event venue',access_instructions:'Coordinate venue access with the event lead.'}).select('id').single());venueIds.push(venue.id)}
const {error:templateErr}=await db.from('checklist_templates').upsert(['Materials counted','Aprons collected','Table covers arranged','Setup completed','Activity started','Return gifts distributed','Clean-up completed','Materials returned'].map((title,i)=>({organization_id:orgId,event_type:'Corporate Workshop',title,priority:i===0?'high':'normal',sort_order:i})),{onConflict:'organization_id,event_type,title'});if(templateErr)throw new Error(templateErr.message);
const today=new Date();const day=(n:number)=>{const d=new Date(today);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const eventDefs=[{name:'Skill-O DIY Crafts Workshop',type:'Corporate Workshop',activity:'Mosaic Art',offset:0,city:'CHN',venue:venueIds[0],status:'active',start:'09:00',end:'16:30',handlers:[h1,h2]},{name:'Brand Activation · Phoenix Marketcity',type:'Birthday Party',activity:'Paint & Plant',offset:2,city:'CHN',venue:venueIds[1],status:'upcoming',start:'10:00',end:'19:00',handlers:[h1,h2]},{name:'Campus Makers Exhibition',type:'Corporate Workshop',activity:'Wooden Truck Making',offset:6,city:'CBE',venue:venueIds[2],status:'upcoming',start:'08:30',end:'17:00',handlers:[h1,h3]}] as const;
for(const e of eventDefs){const date=day(e.offset),cityName=cities.find(c=>c[1]===e.city)![0];let {data:event,error:lookupErr}=await db.from('events').select('id,event_code').eq('organization_id',orgId).eq('name',e.name).eq('city_id',cityRows.get(e.city)!).maybeSingle();if(lookupErr)throw new Error(lookupErr.message);if(event){const {data,error}=await db.from('events').update({event_date:date,status:e.status,start_time:e.start,end_time:e.end}).eq('id',event.id).select('id,event_code').single();if(error)throw new Error(error.message);event=data}else{const {data,error}=await db.from('events').insert({organization_id:orgId,event_code:null,name:e.name,type:e.type,event_date:date,start_time:e.start,end_time:e.end,venue:venueDefs.find(v=>v[1]===e.city&&venueIds[venueDefs.indexOf(v)]===e.venue)![0],venue_id:e.venue,client_id:client.id,activity_id:activities.get(e.activity),address:venueDefs.find(v=>venueIds[venueDefs.indexOf(v)]===e.venue)![2],city:cityName,city_id:cityRows.get(e.city),required_handlers:8,expected_participants:24,organizer_name:'Skill-O Events',created_by:admin,status:e.status}).select('id,event_code').single();if(error)throw new Error(error.message);event=data}
 for(const handler of e.handlers){const {error}=await db.from('event_assignments').upsert({event_id:event.id,handler_id:handler,responsibility:'Lead Instructor',status:'acknowledged'},{onConflict:'event_id,handler_id'});if(error)throw new Error(error.message)}
}
console.log(`Seed complete for Skill-O Crafts. Admin: ananya@skill-o.example. Handlers: arjun@skill-o.example, meera@skill-o.example, rohan@skill-o.example. Demo password is the value you set in DEMO_PASSWORD.`);
