import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';import {hasSupabaseConfig} from '@/lib/supabase/config';
import AdminSection from '@/components/admin-section';

const config:Record<string,{title:string;intro:string;table:string;select:string;order:string;limit?:number}>={
 calendar:{title:'Operations calendar',intro:'A date-led view of published event commitments across your organization.',table:'events',select:'id,event_code,name,type,event_date,expected_arrival_time,client_name,activity:activities(name),city,venue,status,required_handlers,event_assignments(id)',order:'event_date'},
 'live-events':{title:'Live event operations',intro:'Monitor check-ins, late arrivals, checklist progress and open expenses across active events.',table:'events',select:'id,event_code,name,event_date,expected_arrival_time,client_name,activity:activities(name),city,venue,status,required_handlers,event_assignments(id,handler_id),attendance(handler_id,check_in_at,check_out_at,arrival_status),checklist_items(id,completed_at),expenses(id,status,amount)',order:'event_date'},
 attendance:{title:'Attendance register',intro:'Attendance verification records captured for assigned event teams.',table:'attendance',select:'id,event_id,handler_id,check_in_at,check_out_at,arrival_status,review_required,events(name,event_code,event_date,city),profiles(full_name,handler_id)',order:'check_in_at'},
 clients:{title:'Clients',intro:'Organization clients and event relationships.',table:'clients',select:'id,name,company,contact_person,email,home_city_id,created_at',order:'name'},
 venues:{title:'Venues',intro:'Verified venue details and city assignments.',table:'venues',select:'id,name,address,venue_type,city_id,client_id,created_at',order:'name'},
 inventory:{title:'Inventory',intro:'City inventory balances and reorder thresholds.',table:'inventory_items',select:'id,name,unit,quantity_on_hand,reorder_level,city_id,active',order:'name'},
 notifications:{title:'Admin notifications',intro:'Organization notices and operational events addressed to your account.',table:'notifications',select:'id,title,body,kind,href,read_at,created_at',order:'created_at',limit:100},
 'audit-log':{title:'Audit log',intro:'Append-only administrative and operational change history.',table:'audit_log',select:'id,action,target_type,target_id,details,created_at,actor_id,actor_auth_id,city_id',order:'created_at',limit:100},
 reports:{title:'Operations reports',intro:'Export filtered source records for attendance, event completion, handler participation and reimbursements.',table:'expenses',select:'id,event_id,handler_id,category,amount,expense_date,status,review_note,created_at',order:'created_at',limit:500},
 settings:{title:'Organization settings',intro:'Organization identity, city defaults and workspace configuration.',table:'organizations',select:'id,name,slug,created_at',order:'name'},
};
export default async function AdminSectionPage({params}:{params:Promise<{section:string}>}){const {section}=await params,c=config[section];if(!c)return <main className="data-page"><section className="config-notice"><h1>Page not found</h1><p>This workspace page is not available.</p><Link href="/admin">Return to dashboard</Link></section></main>;if(!hasSupabaseConfig())return <main className="data-page"><section className="config-notice"><h1>Connect Supabase</h1><p>Configure the workspace data connection to open {c.title.toLowerCase()}.</p></section></main>;
const db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)return null;const {data,error}=await db.from(c.table as any).select(c.select).order(c.order,{ascending:section==='calendar'||section==='clients'||section==='venues'||section==='inventory'}).limit(c.limit??200);return <AdminSection section={section} title={c.title} intro={c.intro} records={(data??[]) as unknown as Record<string,any>[]} loadError={Boolean(error)}/>}
